---

- name: set ins dir
  set_fact: ins_dir='/home/dhcd/release/{{instance}}'

- name: copy release
  command: chdir={{work_dir}}/relup cp "{{ app }}-{{ old_vsn }}-{{ new_vsn }}.tar.gz" "{{ins_dir}}/releases/{{ app }}_{{ new_vsn }}.tar.gz"

- name: upgrade
  command: chdir="{{ins_dir}}/bin" "./{{ app }}" upgrade  "{{ app }}_{{ new_vsn }}" "{{lv}}"

...
