- name: set release dir
  set_fact: release_dir='/home/dhcd/release'

- name: tar zxvf
  unarchive: src="{{work_dir}}/repo/{{ app }}-{{ vsn }}.tar.gz" dest={{work_dir}}/repo

- name: cp rel
  command: cp -r '{{work_dir}}/repo/{{ app }}-{{ vsn }}' '{{ release_dir }}/{{ instance }}'

- name: delete repo
  file: path={{work_dir}}/repo/{{app}}-{{vsn}} state=absent

- name: delete appcfg
  file: path={{ release_dir }}/{{ instance }}/etc/{{ app }}.config state=absent

- name: delete vmargs
  file: path={{ release_dir }}/{{ instance }}/etc/vm.args state=absent

- name: handler app config
  template: src=appconfig.j2 dest={{ release_dir }}/{{ instance }}/etc/{{ app }}.config

- name: handler vmargs
  template: src=vmargs.j2 dest={{ release_dir }}/{{instance}}/etc/vm.args

- name: start app
  command: chdir={{ release_dir }}/{{instance}}/bin './{{ app }}' start

- name: sleep
  command: sleep 5

- name: ping app
  command: chdir={{ release_dir }}/{{instance}}/bin './{{ app }}' ping
