- name: set mongo dir
  set_fact: mongo_dir='/home/dhcd/mongo'

- name: make entities dir
  file: path='{{mongo_dir}}/{{name}}' state=directory mode=0775

- name: make data dir
  file: path='{{mongo_dir}}/{{name}}/data' state=directory mode=0775
  when: type != "mongos"

- name: mkdir log dir
  file: path='{{mongo_dir}}/{{name}}/log' state=directory mode=0775

- name: make mgo_cfg file
  template: src=mgo_cfg.j2 dest='{{mongo_dir}}/{{name}}/{{name}}.config'

- name: start mongod
  command: chdir='{{mongo_dir}}/{{name}}' /home/dhcd/bin/mongod --config '{{name}}.config'
  when: type != "mongos"

- name: start mongos
  command: chdir='{{mongo_dir}}/{{name}}' /home/dhcd/bin/mongos --config '{{name}}.config'
  when: type == "mongos"

